 ; generated by /home/ntc/src/TetrisGYM/src/nametables/level_menu.js

LEVEL_MENU_SPRITE_COUNT = 55

SPRITE0_TILE = $72
ROW_COUNT = 14
SPRITE0_Y = $26

RESTORE_SCROLL_Y = $98

.macro scrollSleep
; macro because ca65 doesn't like calling a macro on a label
sleepFor 12529
.endmacro

levelMenuSpriteTiles:
    .byte $42,$3B,$3C,$A1,$82,$3B,$3C,$80,$62,$3B,$3C,$61,$40,$3B,$3C,$71,$82,$3B,$3C,$80,$60,$3B,$3C,$83,$70,$3B,$3C,$83,$60,$3B,$3C,$62,$70,$3B,$3C,$40,$80,$3B,$3C,$82,$62,$3B,$3C,$62,$40,$3B,$3C,$72,$82,$3B,$3C,$72,$83,$3B,$3C,$82
levelMenuSpritesX:
    .byte $0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8
levelMenuSpritesY:
    .byte $27,$27,$27,$27,$2F,$2F,$2F,$2F,$37,$37,$37,$37,$3F,$3F,$3F,$3F,$47,$47,$47,$47,$4F,$4F,$4F,$4F,$57,$57,$57,$57,$5F,$5F,$5F,$5F,$67,$67,$67,$67,$6F,$6F,$6F,$6F,$77,$77,$77,$77,$7F,$7F,$7F,$7F,$87,$87,$87,$87,$8F,$8F,$8F,$8F
