 ; generated by /home/ntc/src/TetrisGYM/src/nametables/level_menu.js

LEVEL_MENU_SPRITE_COUNT = 11

SPRITE0_TILE = $60
ROW_COUNT = 3
SPRITE0_Y = $AE

RESTORE_SCROLL_Y = $C8

.macro scrollSleep
; macro because ca65 doesn't like calling a macro on a label
sleepFor 2526
.endmacro

levelMenuSpriteTiles:
    .byte $72,$3B,$3C,$83,$82,$3B,$3C,$80,$83,$3B,$3C,$80
levelMenuSpritesX:
    .byte $0,$8,$F0,$F8,$0,$8,$F0,$F8,$0,$8,$F0,$F8
levelMenuSpritesY:
    .byte $AF,$AF,$AF,$AF,$B7,$B7,$B7,$B7,$BF,$BF,$BF,$BF
