#!/usr/bin/env bash

# does not support whitespace in filenames
mapfile -t sources < <(find -name '*.asm' ! -name 'ram.asm')
mapfile -t variables < <(grep -oP '\w+(?=:\s*\.res)' src/ram.asm)

for variable in "${variables[@]}"; do
    count=$(wc -l < <(grep -P '\b'$variable'\b' "${sources[@]}"))
    if [[ $count = 0 ]]; then
        printf "Unused - %s\n" $variable
    fi
done
