#!/usr/bin/env bash

mapfile -d '' -t sources < <(find -name '*.asm' ! -name 'ram.asm' -print0)

for variable in $(grep -oP '\w+(?=:\s*\.res)' src/ram.asm); do
    if ! grep -q '\b'$variable'\b' "${sources[@]}"; then
        printf "Unused - %s\n" $variable
    fi
done
