; generated by menu.js
autoMenuVars:
menuVarSeedEnabled: .res $01
menuVarSeed: .res $03
menuVarLinecapHow: .res $01
menuVarLinecapWhen: .res $01
menuVarLinecapLevel: .res $01
menuVarLinecapLines: .res $02
menuVarDasOnly: .res $01
menuVarFloor: .res $01
menuVarCrunch: .res $01
menuVarInvisible: .res $01
menuVarGhost: .res $01
menuVarHarddrop: .res $01
menuVarNoLineClear: .res $01
menuVarScrolltris: .res $01
menuVarMirrorHoriz: .res $01
menuVarMirrorVert: .res $01
menuVarCrash: .res $01
menuVarStrictCrash: .res $01
menuVarDisablePause: .res $01
menuVarGoofyFoot: .res $01
menuVarBlockTool: .res $01
menuVarPalMode: .res $01
menuVarQual: .res $01
menuVarKeyboard: .res $01
menuVarScoring: .res $01
menuVarPace: .res $01
menuVarHzDisplay: .res $01
menuVarInputDisplay: .res $01
menuVarDisableFlash: .res $01
menuVarDarkMode: .res $01
menuVarPalette: .res $01
menuVarDas: .res $01
menuVarArr: .res $01
menuVarEntryDelay: .res $01

