; generated by menu.js
; will be overwritten unless built with -M

STRING_PAUSE = stringPause-stringTable
STRING_BLOCK = stringBlock-stringTable
STRING_CLEAR = stringClear-stringTable
STRING_SURE = stringSure-stringTable
STRING_CONFETTI = stringConfetti-stringTable

.enum
MAIN_MENU
SUBMENU_OPTIONS
SUBMENU_TOURNAMENT
SUBMENU_BOARD
SUBMENU_CURSED
SUBMENU_SETTINGS
SUBMENU_DISPLAY
SUBMENU_ANYDAS
MENU_COUNT
.endenum

.out .sprintf("%d/32 menus", MENU_COUNT)


.enum
CHOICESET_OFFON
CHOICESET_KS2FLOORINVIZHALT
CHOICESET_OFFLINESLEVEL
CHOICESET_OFFSHOWTOPCRASH
CHOICESET_CLASSILETTER7DIGITMCAPPEDHIDDEN
CHOICESET_OFFONNEONLITETEALOG
CHOICESET_VANILLPRIDE
CHOICESET_OFFHYDRANKITARU
CHOICESET_COUNT
.endenum

.out .sprintf("%d/32 choicesets", CHOICESET_COUNT)


; index activeMenu
startPageByMenu:
    .byte $00 ; main menu
    .byte $01 ; options
    .byte $02 ; tournament
    .byte $03 ; board
    .byte $04 ; cursed
    .byte $05 ; settings
    .byte $06 ; display
    .byte $07 ; anydas

pageCountByMenu:
    .byte $01 ; main menu
    .byte $01 ; options
    .byte $01 ; tournament
    .byte $01 ; board
    .byte $01 ; cursed
    .byte $01 ; settings
    .byte $01 ; display
    .byte $01 ; anydas

; index activePage
pageTypes:
    .byte PAGE_DEFAULT | MODE_TETRIS ; play tetris1
    .byte PAGE_DEFAULT | MODE_TETRIS ; options
    .byte PAGE_DEFAULT | MODE_DEFAULT ; tournament
    .byte PAGE_DEFAULT | MODE_DEFAULT ; board
    .byte PAGE_DEFAULT | MODE_DEFAULT ; modifiers
    .byte PAGE_DEFAULT | MODE_DEFAULT ; settings
    .byte PAGE_DEFAULT | MODE_DEFAULT ; display
    .byte PAGE_DEFAULT | MODE_DEFAULT ; anydas

itemCountByPage:
    .byte $01 ; play tetris1
    .byte $06 ; options
    .byte $07 ; tournament
    .byte $06 ; board
    .byte $03 ; modifiers
    .byte $08 ; settings
    .byte $07 ; display
    .byte $03 ; anydas

pageLabelsHi:
    .byte >pageLabelsPlayTetris1 ; play tetris1
    .byte >pageLabelsOptions ; options
    .byte >pageLabelsTournament ; tournament
    .byte >pageLabelsBoard ; board
    .byte >pageLabelsModifiers ; modifiers
    .byte >pageLabelsSettings ; settings
    .byte >pageLabelsDisplay ; display
    .byte >pageLabelsAnydas ; anydas

pageLabelsLo:
    .byte <pageLabelsPlayTetris1 ; play tetris1
    .byte <pageLabelsOptions ; options
    .byte <pageLabelsTournament ; tournament
    .byte <pageLabelsBoard ; board
    .byte <pageLabelsModifiers ; modifiers
    .byte <pageLabelsSettings ; settings
    .byte <pageLabelsDisplay ; display
    .byte <pageLabelsAnydas ; anydas

startItemByPage:
    .byte $00 ; PlayTetris1[Mode=Tetris]
    .byte $01 ; Options[Mode=Tetris]
    .byte $07 ; Tournament[Mode=Default]
    .byte $0E ; Board[Mode=Default]
    .byte $14 ; Modifiers[Mode=Default]
    .byte $17 ; Settings[Mode=Default]
    .byte $1F ; Display[Mode=Default]
    .byte $26 ; Anydas[Mode=Default]

; index activeItem
memoryOffsets:
    .byte NORAM ; options
    .byte NORAM ; tournament
    .byte NORAM ; board
    .byte NORAM ; cursed
    .byte NORAM ; settings
    .byte NORAM ; display
    .byte NORAM ; anydas
    .byte <menuVarSeedEnabled ; Seed Enabled
    .byte <menuVarSeed ; seed
    .byte <menuVarLinecapHow ; linecap how
    .byte <menuVarLinecapWhen ; linecap when
    .byte <menuVarLinecapLevel ; linecap level
    .byte <menuVarLinecapLines ; linecap lines
    .byte <menuVarDasOnly ; das only
    .byte <menuVarFloor ; floor
    .byte <menuVarCrunch ; crunch
    .byte <menuVarInvisible ; invisible
    .byte <menuVarGhost ; ghost
    .byte <menuVarHarddrop ; hardDrop
    .byte <menuVarNoLineClear ; no line clear
    .byte <menuVarScrolltris ; scrolltris
    .byte <menuVarMirrorHoriz ; mirror horiz
    .byte <menuVarMirrorVert ; mirror vert
    .byte <menuVarCrash ; crash
    .byte <menuVarStrictCrash ; strict crash
    .byte <menuVarDisablePause ; disable pause
    .byte <menuVarGoofyFoot ; goofy foot
    .byte <menuVarBlockTool ; block tool
    .byte <menuVarPalMode ; pal mode
    .byte <menuVarQual ; qual
    .byte <menuVarKeyboard ; keyboard
    .byte <menuVarScoring ; scoring
    .byte <menuVarPace ; Pace
    .byte <menuVarHzDisplay ; HZ DISPLAY
    .byte <menuVarInputDisplay ; Input Display
    .byte <menuVarDisableFlash ; Disable Flash
    .byte <menuVarDarkMode ; dark mode
    .byte <menuVarPalette ; palette
    .byte <menuVarDas ; das
    .byte <menuVarArr ; arr
    .byte <menuVarEntryDelay ; entry delay

itemTypes:
    .byte TYPE_SUBMENU | SUBMENU_OPTIONS ; options
    .byte TYPE_SUBMENU | SUBMENU_TOURNAMENT ; tournament
    .byte TYPE_SUBMENU | SUBMENU_BOARD ; board
    .byte TYPE_SUBMENU | SUBMENU_CURSED ; cursed
    .byte TYPE_SUBMENU | SUBMENU_SETTINGS ; settings
    .byte TYPE_SUBMENU | SUBMENU_DISPLAY ; display
    .byte TYPE_SUBMENU | SUBMENU_ANYDAS ; anydas
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Seed Enabled
    .byte TYPE_HEX | $06 ; seed
    .byte TYPE_CHOICES | CHOICESET_KS2FLOORINVIZHALT ; linecap how
    .byte TYPE_CHOICES | CHOICESET_OFFLINESLEVEL ; linecap when
    .byte TYPE_NUMBER | $00 ; linecap level
    .byte TYPE_HEX | $04 ; linecap lines
    .byte TYPE_CHOICES | CHOICESET_OFFON ; das only
    .byte TYPE_NUMBER | $10 ; floor
    .byte TYPE_NUMBER | $10 ; crunch
    .byte TYPE_CHOICES | CHOICESET_OFFON ; invisible
    .byte TYPE_CHOICES | CHOICESET_OFFON ; ghost
    .byte TYPE_CHOICES | CHOICESET_OFFON ; hardDrop
    .byte TYPE_CHOICES | CHOICESET_OFFON ; no line clear
    .byte TYPE_CHOICES | CHOICESET_OFFON ; scrolltris
    .byte TYPE_CHOICES | CHOICESET_OFFON ; mirror horiz
    .byte TYPE_CHOICES | CHOICESET_OFFON ; mirror vert
    .byte TYPE_CHOICES | CHOICESET_OFFSHOWTOPCRASH ; crash
    .byte TYPE_CHOICES | CHOICESET_OFFON ; strict crash
    .byte TYPE_CHOICES | CHOICESET_OFFON ; disable pause
    .byte TYPE_CHOICES | CHOICESET_OFFON ; goofy foot
    .byte TYPE_CHOICES | CHOICESET_OFFON ; block tool
    .byte TYPE_CHOICES | CHOICESET_OFFON ; pal mode
    .byte TYPE_CHOICES | CHOICESET_OFFON ; qual
    .byte TYPE_CHOICES | CHOICESET_OFFON ; keyboard
    .byte TYPE_CHOICES | CHOICESET_CLASSILETTER7DIGITMCAPPEDHIDDEN ; scoring
    .byte TYPE_FF_OFF | $10 ; Pace
    .byte TYPE_CHOICES | CHOICESET_OFFON ; HZ DISPLAY
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Input Display
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Disable Flash
    .byte TYPE_CHOICES | CHOICESET_OFFONNEONLITETEALOG ; dark mode
    .byte TYPE_CHOICES | CHOICESET_VANILLPRIDE ; palette
    .byte TYPE_NUMBER | $20 ; das
    .byte TYPE_NUMBER | $20 ; arr
    .byte TYPE_CHOICES | CHOICESET_OFFHYDRANKITARU ; entry delay

choiceSetIndexes:
    .byte choiceSetOffon-choiceSets
    .byte choiceSetKs2floorinvizhalt-choiceSets
    .byte choiceSetOfflineslevel-choiceSets
    .byte choiceSetOffshowtopcrash-choiceSets
    .byte choiceSetClassiletter7digitmcappedhidden-choiceSets
    .byte choiceSetOffonneonlitetealog-choiceSets
    .byte choiceSetVanillpride-choiceSets
    .byte choiceSetOffhydrankitaru-choiceSets

choiceSetCounts:
    .byte $02
    .byte $04
    .byte $03
    .byte $04
    .byte $06
    .byte $06
    .byte $02
    .byte $03

choiceSets:
choiceSetOffon:
    .byte stringOff-choiceSetTable
    .byte stringOn-choiceSetTable
choiceSetKs2floorinvizhalt:
    .byte stringKs2-choiceSetTable
    .byte stringFloor-choiceSetTable
    .byte stringInviz-choiceSetTable
    .byte stringHalt-choiceSetTable
choiceSetOfflineslevel:
    .byte stringOff-choiceSetTable
    .byte stringLines-choiceSetTable
    .byte stringLevel-choiceSetTable
choiceSetOffshowtopcrash:
    .byte stringOff-choiceSetTable
    .byte stringShow-choiceSetTable
    .byte stringTop-choiceSetTable
    .byte stringCrash-choiceSetTable
choiceSetClassiletter7digitmcappedhidden:
    .byte stringClassic-choiceSetTable
    .byte stringLetters-choiceSetTable
    .byte string7digit-choiceSetTable
    .byte stringM-choiceSetTable
    .byte stringCapped-choiceSetTable
    .byte stringHidden-choiceSetTable
choiceSetOffonneonlitetealog:
    .byte stringOff-choiceSetTable
    .byte stringOn-choiceSetTable
    .byte stringNeon-choiceSetTable
    .byte stringLite-choiceSetTable
    .byte stringTeal-choiceSetTable
    .byte stringOg-choiceSetTable
choiceSetVanillpride:
    .byte stringVanilla-choiceSetTable
    .byte stringPride-choiceSetTable
choiceSetOffhydrankitaru:
    .byte stringOff-choiceSetTable
    .byte stringHydrant-choiceSetTable
    .byte stringKitaru-choiceSetTable

stringTable:
stringPause:
    .byte $05,"P","A","U","S","E"
stringBlock:
    .byte $05,"B","L","O","C","K"
stringClear:
    .byte $06,"C","L","E","A","R","?"
stringSure:
    .byte $06,"S","U","R","E","?","!"
stringConfetti:
    .byte $08,"C","O","N","F","E","T","T","I"

.out .sprintf("%d/256 sprite string bytes", * - stringTable)

choiceSetTable:
stringOff:
    .byte $03,"O","F","F"
stringOn:
    .byte $02,"O","N"
stringKs2:
    .byte $04,"K","S",$69,"2"
stringFloor:
    .byte $05,"F","L","O","O","R"
stringInviz:
    .byte $05,"I","N","V","I","Z"
stringHalt:
    .byte $04,"H","A","L","T"
stringLines:
    .byte $05,"L","I","N","E","S"
stringLevel:
    .byte $05,"L","E","V","E","L"
stringShow:
    .byte $04,"S","H","O","W"
stringTop:
    .byte $03,"T","O","P"
stringCrash:
    .byte $05,"C","R","A","S","H"
stringClassic:
    .byte $07,"C","L","A","S","S","I","C"
stringLetters:
    .byte $07,"L","E","T","T","E","R","S"
string7digit:
    .byte $06,"7","D","I","G","I","T"
stringM:
    .byte $01,"M"
stringCapped:
    .byte $06,"C","A","P","P","E","D"
stringHidden:
    .byte $06,"H","I","D","D","E","N"
stringNeon:
    .byte $04,"N","E","O","N"
stringLite:
    .byte $04,"L","I","T","E"
stringTeal:
    .byte $04,"T","E","A","L"
stringOg:
    .byte $02,"O","G"
stringVanilla:
    .byte $07,"V","A","N","I","L","L","A"
stringPride:
    .byte $05,"P","R","I","D","E"
stringHydrant:
    .byte $07,"H","Y","D","R","A","N","T"
stringKitaru:
    .byte $06,"K","I","T","A","R","U"

.out .sprintf("%d/256 choice set bytes", * - choiceSetTable)


pageLabelsPlayTetris1:
    .byte $EF,"P","L","A","Y",$EF,"T","E","T","R","I","S","1"
    .byte EOL
    .byte "O","P","T","I","O","N","S"
    .byte EOF
pageLabelsOptions:
    .byte $EF,$EF,$EF,$EF,"O","P","T","I","O","N","S"
    .byte EOL
    .byte "T","O","U","R","N","A","M","E","N","T"
    .byte EOL
    .byte "B","O","A","R","D"
    .byte EOL
    .byte "C","U","R","S","E","D"
    .byte EOL
    .byte "S","E","T","T","I","N","G","S"
    .byte EOL
    .byte "D","I","S","P","L","A","Y"
    .byte EOL
    .byte "A","N","Y","D","A","S"
    .byte EOF
pageLabelsTournament:
    .byte $EF,$EF,"T","O","U","R","N","A","M","E","N","T"
    .byte EOL
    .byte "S","E","E","D",$EF,"E","N","A","B","L","E","D"
    .byte EOL
    .byte "S","E","E","D"
    .byte EOL
    .byte "L","I","N","E","C","A","P",$EF,"H","O","W"
    .byte EOL
    .byte "L","I","N","E","C","A","P",$EF,"W","H","E","N"
    .byte EOL
    .byte "L","I","N","E","C","A","P",$EF,"L","E","V","E","L"
    .byte EOL
    .byte "L","I","N","E","C","A","P",$EF,"L","I","N","E","S"
    .byte EOL
    .byte "D","A","S",$EF,"O","N","L","Y"
    .byte EOF
pageLabelsBoard:
    .byte $EF,$EF,$EF,$EF,$EF,"B","O","A","R","D"
    .byte EOL
    .byte "F","L","O","O","R"
    .byte EOL
    .byte "C","R","U","N","C","H"
    .byte EOL
    .byte "I","N","V","I","S","I","B","L","E"
    .byte EOL
    .byte "G","H","O","S","T"
    .byte EOL
    .byte "H","A","R","D","D","R","O","P"
    .byte EOL
    .byte "N","O",$EF,"L","I","N","E",$EF,"C","L","E","A","R"
    .byte EOF
pageLabelsModifiers:
    .byte $EF,$EF,$EF,"M","O","D","I","F","I","E","R","S"
    .byte EOL
    .byte "S","C","R","O","L","L","T","R","I","S"
    .byte EOL
    .byte "M","I","R","R","O","R",$EF,"H","O","R","I","Z"
    .byte EOL
    .byte "M","I","R","R","O","R",$EF,"V","E","R","T"
    .byte EOF
pageLabelsSettings:
    .byte $EF,$EF,$EF,"S","E","T","T","I","N","G","S"
    .byte EOL
    .byte "C","R","A","S","H"
    .byte EOL
    .byte "S","T","R","I","C","T",$EF,"C","R","A","S","H"
    .byte EOL
    .byte "D","I","S","A","B","L","E",$EF,"P","A","U","S","E"
    .byte EOL
    .byte "G","O","O","F","Y",$EF,"F","O","O","T"
    .byte EOL
    .byte "B","L","O","C","K",$EF,"T","O","O","L"
    .byte EOL
    .byte "P","A","L",$EF,"M","O","D","E"
    .byte EOL
    .byte "Q","U","A","L"
    .byte EOL
    .byte "K","E","Y","B","O","A","R","D"
    .byte EOF
pageLabelsDisplay:
    .byte $EF,$EF,$EF,$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "S","C","O","R","I","N","G"
    .byte EOL
    .byte "P","A","C","E"
    .byte EOL
    .byte "H","Z",$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "I","N","P","U","T",$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "D","I","S","A","B","L","E",$EF,"F","L","A","S","H"
    .byte EOL
    .byte "D","A","R","K",$EF,"M","O","D","E"
    .byte EOL
    .byte "P","A","L","E","T","T","E"
    .byte EOF
pageLabelsAnydas:
    .byte $EF,$EF,$EF,$EF,"A","N","Y","D","A","S"
    .byte EOL
    .byte "D","A","S"
    .byte EOL
    .byte "A","R","R"
    .byte EOL
    .byte "E","N","T","R","Y",$EF,"D","E","L","A","Y"
    .byte EOF

