; generated by menu.js
; will be overwritten unless built with -M

STRING_PAUSE = stringPause-stringTable
STRING_BLOCK = stringBlock-stringTable
STRING_CLEAR = stringClear-stringTable
STRING_SURE = stringSure-stringTable
STRING_CONFETTI = stringConfetti-stringTable

.enum
MAIN_MENU
SUBMENU_BOOLEANS
SUBMENU_NUMBERS
SUBMENU_DIGITS
SUBMENU_32BYTES
SUBMENU_DEBUG
SUBMENU_A
SUBMENU_TOURNAMENT
SUBMENU_DISPLAY
SUBMENU_SETTINGS
MENU_COUNT
.endenum

.out .sprintf("%d/32 menus", MENU_COUNT)


.enum
CHOICESET_TETTSPSEESTAPACSETBTFLOCRUQCKTRNMARTAPCKRGARLOBDASLOWKILINVHRD
CHOICESET_OFFON
CHOICESET_ONOFF
CHOICESET_AB
CHOICESET_OFFONABSHOWTOPCRASHNEONLITETEALOGCLASSILETTER7DIGITMCAPPEDHIDDENLINESLEVELKS2FLOORINVIZHALTTETTSPSEESTAPACSETBTFLOCRUQCKTRNMARTAPCKRGARLOBDASLOWKILINVHRDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CHOICESET_LINESLEVEL
CHOICESET_KS2FLOORINVIZHALT
CHOICESET_CLASSILETTER7DIGITMCAPPEDHIDDEN
CHOICESET_OFFONNEONLITETEALOG
CHOICESET_OFFSHOWTOPCRASH
CHOICESET_COUNT
.endenum

.out .sprintf("%d/32 choicesets", CHOICESET_COUNT)


; index activeMenu
startPageByMenu:
    .byte $00 ; main menu
    .byte $03 ; booleans
    .byte $05 ; numbers
    .byte $07 ; Digits
    .byte $0A ; 32 bytes
    .byte $0B ; debug
    .byte $0C ; a
    .byte $0D ; Tournament
    .byte $0F ; Display
    .byte $11 ; Settings

pageCountByMenu:
    .byte $03 ; main menu
    .byte $02 ; booleans
    .byte $02 ; numbers
    .byte $03 ; Digits
    .byte $01 ; 32 bytes
    .byte $01 ; debug
    .byte $01 ; a
    .byte $02 ; Tournament
    .byte $02 ; Display
    .byte $02 ; Settings

; index activePage
pageTypes:
    .byte PAGE_DEFAULT | MODE_DEFAULT ; (new menu,*)?!
    .byte PAGE_DEFAULT | MODE_DEFAULT ; kinda working
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg
    .byte PAGE_DEFAULT | MODE_DEFAULT ; boolean
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg
    .byte PAGE_DEFAULT | MODE_DEFAULT ; Numbers
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg
    .byte PAGE_DEFAULT | MODE_DEFAULT ; BCD
    .byte PAGE_DEFAULT | MODE_DEFAULT ; Hex
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg
    .byte PAGE_DEFAULT | MODE_DEFAULT ; 07**
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg
    .byte PAGE_DEFAULT | MODE_DEFAULT ; aaaaaaaaaaaaaa
    .byte PAGE_DEFAULT | MODE_DEFAULT ; Tournament
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg
    .byte PAGE_DEFAULT | MODE_DEFAULT ; Display
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg
    .byte PAGE_DEFAULT | MODE_DEFAULT ; Settings
    .byte PAGE_DEFAULT | MODE_DEFAULT ; dbg

itemCountByPage:
    .byte $06 ; (new menu,*)?!
    .byte $04 ; kinda working
    .byte $05 ; dbg
    .byte $04 ; boolean
    .byte $05 ; dbg
    .byte $07 ; Numbers
    .byte $05 ; dbg
    .byte $04 ; BCD
    .byte $04 ; Hex
    .byte $05 ; dbg
    .byte $08 ; 07**
    .byte $05 ; dbg
    .byte $08 ; aaaaaaaaaaaaaa
    .byte $08 ; Tournament
    .byte $05 ; dbg
    .byte $06 ; Display
    .byte $05 ; dbg
    .byte $06 ; Settings
    .byte $05 ; dbg

pageLabelsHi:
    .byte >pageLabelsNewMenu ; (new menu,*)?!
    .byte >pageLabelsKindaWorking ; kinda working
    .byte >pageLabelsDbg ; dbg
    .byte >pageLabelsBoolean ; boolean
    .byte >pageLabelsDbg ; dbg
    .byte >pageLabelsNumbers ; Numbers
    .byte >pageLabelsDbg ; dbg
    .byte >pageLabelsBcd ; BCD
    .byte >pageLabelsHex ; Hex
    .byte >pageLabelsDbg ; dbg
    .byte >pageLabels07 ; 07**
    .byte >pageLabelsDbg ; dbg
    .byte >pageLabelsAaaaaaaaaaaaaa ; aaaaaaaaaaaaaa
    .byte >pageLabelsTournament ; Tournament
    .byte >pageLabelsDbg ; dbg
    .byte >pageLabelsDisplay ; Display
    .byte >pageLabelsDbg ; dbg
    .byte >pageLabelsSettings ; Settings
    .byte >pageLabelsDbg ; dbg

pageLabelsLo:
    .byte <pageLabelsNewMenu ; (new menu,*)?!
    .byte <pageLabelsKindaWorking ; kinda working
    .byte <pageLabelsDbg ; dbg
    .byte <pageLabelsBoolean ; boolean
    .byte <pageLabelsDbg ; dbg
    .byte <pageLabelsNumbers ; Numbers
    .byte <pageLabelsDbg ; dbg
    .byte <pageLabelsBcd ; BCD
    .byte <pageLabelsHex ; Hex
    .byte <pageLabelsDbg ; dbg
    .byte <pageLabels07 ; 07**
    .byte <pageLabelsDbg ; dbg
    .byte <pageLabelsAaaaaaaaaaaaaa ; aaaaaaaaaaaaaa
    .byte <pageLabelsTournament ; Tournament
    .byte <pageLabelsDbg ; dbg
    .byte <pageLabelsDisplay ; Display
    .byte <pageLabelsDbg ; dbg
    .byte <pageLabelsSettings ; Settings
    .byte <pageLabelsDbg ; dbg

startItemByPage:
    .byte $00 ; NewMenu
    .byte $06 ; KindaWorking
    .byte $0A ; Dbg
    .byte $0F ; Boolean
    .byte $13 ; Dbg
    .byte $18 ; Numbers
    .byte $1F ; Dbg
    .byte $24 ; Bcd
    .byte $28 ; Hex
    .byte $2C ; Dbg
    .byte $31 ; 07
    .byte $39 ; Dbg
    .byte $3E ; Aaaaaaaaaaaaaa
    .byte $46 ; Tournament[Mode=Default]
    .byte $4E ; Dbg
    .byte $53 ; Display
    .byte $59 ; Dbg
    .byte $5E ; Settings
    .byte $64 ; Dbg

; index activeItem
memoryOffsets:
    .byte NORAM ; booleans
    .byte NORAM ; numbers
    .byte NORAM ; Digits
    .byte NORAM ; 32 bytes
    .byte NORAM ; debug
    .byte NORAM ; a
    .byte <practiseType ; practise
    .byte NORAM ; Tournament
    .byte NORAM ; Display
    .byte NORAM ; Settings
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr
    .byte <menuVarA ; A
    .byte <menuVarA ; B
    .byte <menuVarA ; C
    .byte <menuVarA ; D
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr
    .byte <menuVarMax2 ; MAX 2
    .byte <menuVarMax2 ; MaX 30
    .byte <menuVarMax2 ; no max
    .byte <menuVarMax2 ; -1 is off
    .byte <menuVarWords ; words
    .byte <menuVarWords ; by digit
    .byte <menuVarWords ; by bcd digit
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr
    .byte <menuVar8 ; 2
    .byte <menuVar8 ; 4
    .byte <menuVar8 ; 6
    .byte <menuVar8 ; 8
    .byte <menuVar8+3 ; 2
    .byte <menuVar8+2 ; 4
    .byte <menuVar8+1 ; 6
    .byte <menuVar8 ; 8
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr
    .byte <highscores ; 00-03
    .byte <highscores+4 ; 04-07
    .byte <highscores+8 ; 08-0B
    .byte <highscores+12 ; 0C-0F
    .byte <highscores+16 ; 10-13
    .byte <highscores+20 ; 14-17
    .byte <highscores+24 ; 18-1B
    .byte <highscores+28 ; 1C-1F
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <menuVarAaaaaaaaaaaa ; aaaaaaaaaaaa
    .byte <set_seed_input ; SEED
    .byte <linecapFlag ; linecap
    .byte <linecapWhen ; when
    .byte <linecapHow ; how
    .byte <linecapLevel ; Level
    .byte <linecapLines ; Lines
    .byte <dasOnlyFlag ; Das
    .byte <qualFlag ; Qual
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr
    .byte <scoringModifier ; Scoring
    .byte <paceModifier ; Pace
    .byte <hzFlag ; HZ DISPLAY
    .byte <inputDisplayFlag ; Input Display
    .byte <disableFlashFlag ; Disable Flash
    .byte <darkModifier ; Dark Mode
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr
    .byte <crashModifier ; Crash
    .byte <strictFlag ; Strict Crash
    .byte <disablePauseFlag ; Disable Pause
    .byte <goofyFlag ; Goofy Foot
    .byte <debugFlag ; Block Tool
    .byte <palFlag ; Pal Mode
    .byte <activeMenu ; menu
    .byte <activePage ; page
    .byte <activeRow ; row
    .byte <activeColumn ; col
    .byte <menuStackPtr ; ptr

itemTypes:
    .byte TYPE_SUBMENU | SUBMENU_BOOLEANS ; booleans
    .byte TYPE_SUBMENU | SUBMENU_NUMBERS ; numbers
    .byte TYPE_SUBMENU | SUBMENU_DIGITS ; Digits
    .byte TYPE_SUBMENU | SUBMENU_32BYTES ; 32 bytes
    .byte TYPE_SUBMENU | SUBMENU_DEBUG ; debug
    .byte TYPE_SUBMENU | SUBMENU_A ; a
    .byte TYPE_CHOICES | CHOICESET_TETTSPSEESTAPACSETBTFLOCRUQCKTRNMARTAPCKRGARLOBDASLOWKILINVHRD ; practise
    .byte TYPE_SUBMENU | SUBMENU_TOURNAMENT ; Tournament
    .byte TYPE_SUBMENU | SUBMENU_DISPLAY ; Display
    .byte TYPE_SUBMENU | SUBMENU_SETTINGS ; Settings
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr
    .byte TYPE_CHOICES | CHOICESET_OFFON ; A
    .byte TYPE_CHOICES | CHOICESET_ONOFF ; B
    .byte TYPE_NUMBER | $02 ; C
    .byte TYPE_CHOICES | CHOICESET_AB ; D
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr
    .byte TYPE_NUMBER | $02 ; MAX 2
    .byte TYPE_NUMBER | $1F ; MaX 30
    .byte TYPE_NUMBER | $00 ; no max
    .byte TYPE_FF_OFF | $00 ; -1 is off
    .byte TYPE_CHOICES | CHOICESET_OFFONABSHOWTOPCRASHNEONLITETEALOGCLASSILETTER7DIGITMCAPPEDHIDDENLINESLEVELKS2FLOORINVIZHALTTETTSPSEESTAPACSETBTFLOCRUQCKTRNMARTAPCKRGARLOBDASLOWKILINVHRDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; words
    .byte TYPE_HEX | $02 ; by digit
    .byte TYPE_BCD | $02 ; by bcd digit
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr
    .byte TYPE_BCD | $02 ; 2
    .byte TYPE_BCD | $04 ; 4
    .byte TYPE_BCD | $06 ; 6
    .byte TYPE_BCD | $08 ; 8
    .byte TYPE_HEX | $02 ; 2
    .byte TYPE_HEX | $04 ; 4
    .byte TYPE_HEX | $06 ; 6
    .byte TYPE_HEX | $08 ; 8
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr
    .byte TYPE_HEX | $08 ; 00-03
    .byte TYPE_HEX | $08 ; 04-07
    .byte TYPE_HEX | $08 ; 08-0B
    .byte TYPE_HEX | $08 ; 0C-0F
    .byte TYPE_HEX | $08 ; 10-13
    .byte TYPE_HEX | $08 ; 14-17
    .byte TYPE_HEX | $08 ; 18-1B
    .byte TYPE_HEX | $08 ; 1C-1F
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_CHOICES | CHOICESET_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ; aaaaaaaaaaaa
    .byte TYPE_HEX | $06 ; SEED
    .byte TYPE_CHOICES | CHOICESET_OFFON ; linecap
    .byte TYPE_CHOICES | CHOICESET_LINESLEVEL ; when
    .byte TYPE_CHOICES | CHOICESET_KS2FLOORINVIZHALT ; how
    .byte TYPE_NUMBER | $00 ; Level
    .byte TYPE_HEX | $04 ; Lines
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Das
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Qual
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr
    .byte TYPE_CHOICES | CHOICESET_CLASSILETTER7DIGITMCAPPEDHIDDEN ; Scoring
    .byte TYPE_FF_OFF | $10 ; Pace
    .byte TYPE_CHOICES | CHOICESET_OFFON ; HZ DISPLAY
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Input Display
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Disable Flash
    .byte TYPE_CHOICES | CHOICESET_OFFONNEONLITETEALOG ; Dark Mode
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr
    .byte TYPE_CHOICES | CHOICESET_OFFSHOWTOPCRASH ; Crash
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Strict Crash
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Disable Pause
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Goofy Foot
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Block Tool
    .byte TYPE_CHOICES | CHOICESET_OFFON ; Pal Mode
    .byte TYPE_NUMBER | $00 ; menu
    .byte TYPE_NUMBER | $00 ; page
    .byte TYPE_NUMBER | $00 ; row
    .byte TYPE_NUMBER | $00 ; col
    .byte TYPE_NUMBER | $00 ; ptr

choiceSetIndexes:
    .byte choiceSetTettspseestapacsetbtflocruqcktrnmartapckrgarlobdaslowkilinvhrd-choiceSets
    .byte choiceSetOffon-choiceSets
    .byte choiceSetOnoff-choiceSets
    .byte choiceSetAb-choiceSets
    .byte choiceSetOffonabshowtopcrashneonlitetealogclassiletter7digitmcappedhiddenlineslevelks2floorinvizhalttettspseestapacsetbtflocruqcktrnmartapckrgarlobdaslowkilinvhrdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-choiceSets
    .byte choiceSetAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-choiceSets
    .byte choiceSetLineslevel-choiceSets
    .byte choiceSetKs2floorinvizhalt-choiceSets
    .byte choiceSetClassiletter7digitmcappedhidden-choiceSets
    .byte choiceSetOffonneonlitetealog-choiceSets
    .byte choiceSetOffshowtopcrash-choiceSets

choiceSetCounts:
    .byte $15
    .byte $02
    .byte $02
    .byte $02
    .byte $34
    .byte $08
    .byte $02
    .byte $04
    .byte $06
    .byte $06
    .byte $04

choiceSets:
choiceSetTettspseestapacsetbtflocruqcktrnmartapckrgarlobdaslowkilinvhrd:
    .byte stringTet-choiceSetTable
    .byte stringTsp-choiceSetTable
    .byte stringSee-choiceSetTable
    .byte stringSta-choiceSetTable
    .byte stringPac-choiceSetTable
    .byte stringSet-choiceSetTable
    .byte stringBT-choiceSetTable
    .byte stringFlo-choiceSetTable
    .byte stringCru-choiceSetTable
    .byte stringQck-choiceSetTable
    .byte stringTrn-choiceSetTable
    .byte stringMar-choiceSetTable
    .byte stringTap-choiceSetTable
    .byte stringCkr-choiceSetTable
    .byte stringGar-choiceSetTable
    .byte stringLob-choiceSetTable
    .byte stringDas-choiceSetTable
    .byte stringLow-choiceSetTable
    .byte stringKil-choiceSetTable
    .byte stringInv-choiceSetTable
    .byte stringHrd-choiceSetTable
choiceSetOffon:
    .byte stringOff-choiceSetTable
    .byte stringOn-choiceSetTable
choiceSetOnoff:
    .byte stringOn-choiceSetTable
    .byte stringOff-choiceSetTable
choiceSetAb:
    .byte stringA-choiceSetTable
    .byte stringB-choiceSetTable
choiceSetOffonabshowtopcrashneonlitetealogclassiletter7digitmcappedhiddenlineslevelks2floorinvizhalttettspseestapacsetbtflocruqcktrnmartapckrgarlobdaslowkilinvhrdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:
    .byte stringOff-choiceSetTable
    .byte stringOn-choiceSetTable
    .byte stringA-choiceSetTable
    .byte stringB-choiceSetTable
    .byte stringShow-choiceSetTable
    .byte stringTop-choiceSetTable
    .byte stringCrash-choiceSetTable
    .byte stringNeon-choiceSetTable
    .byte stringLite-choiceSetTable
    .byte stringTeal-choiceSetTable
    .byte stringOg-choiceSetTable
    .byte stringClassic-choiceSetTable
    .byte stringLetters-choiceSetTable
    .byte string7digit-choiceSetTable
    .byte stringM-choiceSetTable
    .byte stringCapped-choiceSetTable
    .byte stringHidden-choiceSetTable
    .byte stringLines-choiceSetTable
    .byte stringLevel-choiceSetTable
    .byte stringKs2-choiceSetTable
    .byte stringFloor-choiceSetTable
    .byte stringInviz-choiceSetTable
    .byte stringHalt-choiceSetTable
    .byte stringTet-choiceSetTable
    .byte stringTsp-choiceSetTable
    .byte stringSee-choiceSetTable
    .byte stringSta-choiceSetTable
    .byte stringPac-choiceSetTable
    .byte stringSet-choiceSetTable
    .byte stringBT-choiceSetTable
    .byte stringFlo-choiceSetTable
    .byte stringCru-choiceSetTable
    .byte stringQck-choiceSetTable
    .byte stringTrn-choiceSetTable
    .byte stringMar-choiceSetTable
    .byte stringTap-choiceSetTable
    .byte stringCkr-choiceSetTable
    .byte stringGar-choiceSetTable
    .byte stringLob-choiceSetTable
    .byte stringDas-choiceSetTable
    .byte stringLow-choiceSetTable
    .byte stringKil-choiceSetTable
    .byte stringInv-choiceSetTable
    .byte stringHrd-choiceSetTable
    .byte stringA-choiceSetTable
    .byte stringAa-choiceSetTable
    .byte stringAaa-choiceSetTable
    .byte stringAaaa-choiceSetTable
    .byte stringAaaaa-choiceSetTable
    .byte stringAaaaaa-choiceSetTable
    .byte stringAaaaaaa-choiceSetTable
    .byte stringAaaaaaaa-choiceSetTable
choiceSetAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:
    .byte stringA-choiceSetTable
    .byte stringAa-choiceSetTable
    .byte stringAaa-choiceSetTable
    .byte stringAaaa-choiceSetTable
    .byte stringAaaaa-choiceSetTable
    .byte stringAaaaaa-choiceSetTable
    .byte stringAaaaaaa-choiceSetTable
    .byte stringAaaaaaaa-choiceSetTable
choiceSetLineslevel:
    .byte stringLines-choiceSetTable
    .byte stringLevel-choiceSetTable
choiceSetKs2floorinvizhalt:
    .byte stringKs2-choiceSetTable
    .byte stringFloor-choiceSetTable
    .byte stringInviz-choiceSetTable
    .byte stringHalt-choiceSetTable
choiceSetClassiletter7digitmcappedhidden:
    .byte stringClassic-choiceSetTable
    .byte stringLetters-choiceSetTable
    .byte string7digit-choiceSetTable
    .byte stringM-choiceSetTable
    .byte stringCapped-choiceSetTable
    .byte stringHidden-choiceSetTable
choiceSetOffonneonlitetealog:
    .byte stringOff-choiceSetTable
    .byte stringOn-choiceSetTable
    .byte stringNeon-choiceSetTable
    .byte stringLite-choiceSetTable
    .byte stringTeal-choiceSetTable
    .byte stringOg-choiceSetTable
choiceSetOffshowtopcrash:
    .byte stringOff-choiceSetTable
    .byte stringShow-choiceSetTable
    .byte stringTop-choiceSetTable
    .byte stringCrash-choiceSetTable

stringTable:
stringPause:
    .byte $05,"P","A","U","S","E"
stringBlock:
    .byte $05,"B","L","O","C","K"
stringClear:
    .byte $06,"C","L","E","A","R","?"
stringSure:
    .byte $06,"S","U","R","E","?","!"
stringConfetti:
    .byte $08,"C","O","N","F","E","T","T","I"

.out .sprintf("%d/256 sprite string bytes", * - stringTable)

choiceSetTable:
stringTet:
    .byte $03,"T","E","T"
stringTsp:
    .byte $03,"T","S","P"
stringSee:
    .byte $03,"S","E","E"
stringSta:
    .byte $03,"S","T","A"
stringPac:
    .byte $03,"P","A","C"
stringSet:
    .byte $03,"S","E","T"
stringBT:
    .byte $03,"B","-","T"
stringFlo:
    .byte $03,"F","L","O"
stringCru:
    .byte $03,"C","R","U"
stringQck:
    .byte $03,"Q","C","K"
stringTrn:
    .byte $03,"T","R","N"
stringMar:
    .byte $03,"M","A","R"
stringTap:
    .byte $03,"T","A","P"
stringCkr:
    .byte $03,"C","K","R"
stringGar:
    .byte $03,"G","A","R"
stringLob:
    .byte $03,"L","O","B"
stringDas:
    .byte $03,"D","A","S"
stringLow:
    .byte $03,"L","O","W"
stringKil:
    .byte $03,"K","I","L"
stringInv:
    .byte $03,"I","N","V"
stringHrd:
    .byte $03,"H","R","D"
stringOff:
    .byte $03,"O","F","F"
stringOn:
    .byte $02,"O","N"
stringA:
    .byte $01,"A"
stringB:
    .byte $01,"B"
stringShow:
    .byte $04,"S","H","O","W"
stringTop:
    .byte $03,"T","O","P"
stringCrash:
    .byte $05,"C","R","A","S","H"
stringNeon:
    .byte $04,"N","E","O","N"
stringLite:
    .byte $04,"L","I","T","E"
stringTeal:
    .byte $04,"T","E","A","L"
stringOg:
    .byte $02,"O","G"
stringClassic:
    .byte $07,"C","L","A","S","S","I","C"
stringLetters:
    .byte $07,"L","E","T","T","E","R","S"
string7digit:
    .byte $06,"7","D","I","G","I","T"
stringM:
    .byte $01,"M"
stringCapped:
    .byte $06,"C","A","P","P","E","D"
stringHidden:
    .byte $06,"H","I","D","D","E","N"
stringLines:
    .byte $05,"L","I","N","E","S"
stringLevel:
    .byte $05,"L","E","V","E","L"
stringKs2:
    .byte $04,"K","S",$69,"2"
stringFloor:
    .byte $05,"F","L","O","O","R"
stringInviz:
    .byte $05,"I","N","V","I","Z"
stringHalt:
    .byte $04,"H","A","L","T"
stringAa:
    .byte $02,"A","A"
stringAaa:
    .byte $03,"A","A","A"
stringAaaa:
    .byte $04,"A","A","A","A"
stringAaaaa:
    .byte $05,"A","A","A","A","A"
stringAaaaaa:
    .byte $06,"A","A","A","A","A","A"
stringAaaaaaa:
    .byte $07,"A","A","A","A","A","A","A"
stringAaaaaaaa:
    .byte $08,"A","A","A","A","A","A","A","A"

.out .sprintf("%d/256 choice set bytes", * - choiceSetTable)


pageLabelsNewMenu:
    .byte $5E,"N","E","W",$EF,"M","E","N","U",$25,$69,$5F,"?","!"
    .byte EOL
    .byte "B","O","O","L","E","A","N","S"
    .byte EOL
    .byte "N","U","M","B","E","R","S"
    .byte EOL
    .byte "D","I","G","I","T","S"
    .byte EOL
    .byte "3","2",$EF,"B","Y","T","E","S"
    .byte EOL
    .byte "D","E","B","U","G"
    .byte EOL
    .byte "A"
    .byte EOF
pageLabelsKindaWorking:
    .byte $EF,"K","I","N","D","A",$EF,"W","O","R","K","I","N","G"
    .byte EOL
    .byte "P","R","A","C","T","I","S","E"
    .byte EOL
    .byte "T","O","U","R","N","A","M","E","N","T"
    .byte EOL
    .byte "D","I","S","P","L","A","Y"
    .byte EOL
    .byte "S","E","T","T","I","N","G","S"
    .byte EOF
pageLabelsDbg:
    .byte $EF,$EF,$EF,$EF,$EF,$EF,"D","B","G"
    .byte EOL
    .byte "M","E","N","U"
    .byte EOL
    .byte "P","A","G","E"
    .byte EOL
    .byte "R","O","W"
    .byte EOL
    .byte "C","O","L"
    .byte EOL
    .byte "P","T","R"
    .byte EOF
pageLabelsBoolean:
    .byte $EF,$EF,$EF,$EF,"B","O","O","L","E","A","N"
    .byte EOL
    .byte "A"
    .byte EOL
    .byte "B"
    .byte EOL
    .byte "C"
    .byte EOL
    .byte "D"
    .byte EOF

pageLabelsNumbers:
    .byte $EF,$EF,$EF,$EF,"N","U","M","B","E","R","S"
    .byte EOL
    .byte "M","A","X",$EF,"2"
    .byte EOL
    .byte "M","A","X",$EF,"3","0"
    .byte EOL
    .byte "N","O",$EF,"M","A","X"
    .byte EOL
    .byte "-","1",$EF,"I","S",$EF,"O","F","F"
    .byte EOL
    .byte "W","O","R","D","S"
    .byte EOL
    .byte "B","Y",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "B","Y",$EF,"B","C","D",$EF,"D","I","G","I","T"
    .byte EOF

pageLabelsBcd:
    .byte $EF,$EF,$EF,$EF,$EF,$EF,"B","C","D"
    .byte EOL
    .byte "2"
    .byte EOL
    .byte "4"
    .byte EOL
    .byte "6"
    .byte EOL
    .byte "8"
    .byte EOF
pageLabelsHex:
    .byte $EF,$EF,$EF,$EF,$EF,$EF,"H","E","X"
    .byte EOL
    .byte "2"
    .byte EOL
    .byte "4"
    .byte EOL
    .byte "6"
    .byte EOL
    .byte "8"
    .byte EOF

pageLabels07:
    .byte $EF,$EF,$EF,$EF,$EF,"0","7",$69,$69
    .byte EOL
    .byte "0","0","-","0","3"
    .byte EOL
    .byte "0","4","-","0","7"
    .byte EOL
    .byte "0","8","-","0","B"
    .byte EOL
    .byte "0","C","-","0","F"
    .byte EOL
    .byte "1","0","-","1","3"
    .byte EOL
    .byte "1","4","-","1","7"
    .byte EOL
    .byte "1","8","-","1","B"
    .byte EOL
    .byte "1","C","-","1","F"
    .byte EOF

pageLabelsAaaaaaaaaaaaaa:
    .byte "A","A","A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOL
    .byte "A","A","A","A","A","A","A","A","A","A","A","A"
    .byte EOF
pageLabelsTournament:
    .byte $EF,$EF,"T","O","U","R","N","A","M","E","N","T"
    .byte EOL
    .byte "S","E","E","D"
    .byte EOL
    .byte "L","I","N","E","C","A","P"
    .byte EOL
    .byte "W","H","E","N"
    .byte EOL
    .byte "H","O","W"
    .byte EOL
    .byte "L","E","V","E","L"
    .byte EOL
    .byte "L","I","N","E","S"
    .byte EOL
    .byte "D","A","S"
    .byte EOL
    .byte "Q","U","A","L"
    .byte EOF

pageLabelsDisplay:
    .byte $EF,$EF,$EF,$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "S","C","O","R","I","N","G"
    .byte EOL
    .byte "P","A","C","E"
    .byte EOL
    .byte "H","Z",$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "I","N","P","U","T",$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "D","I","S","A","B","L","E",$EF,"F","L","A","S","H"
    .byte EOL
    .byte "D","A","R","K",$EF,"M","O","D","E"
    .byte EOF

pageLabelsSettings:
    .byte $EF,$EF,$EF,"S","E","T","T","I","N","G","S"
    .byte EOL
    .byte "C","R","A","S","H"
    .byte EOL
    .byte "S","T","R","I","C","T",$EF,"C","R","A","S","H"
    .byte EOL
    .byte "D","I","S","A","B","L","E",$EF,"P","A","U","S","E"
    .byte EOL
    .byte "G","O","O","F","Y",$EF,"F","O","O","T"
    .byte EOL
    .byte "B","L","O","C","K",$EF,"T","O","O","L"
    .byte EOL
    .byte "P","A","L",$EF,"M","O","D","E"
    .byte EOF


