.ifndef INES_MAPPER ; is set via ca65 flags
INES_MAPPER := 1000 ; 0 (NROM), 1 (MMC1), 3 (CNROM), 4 (MMC3), 5 (MMC5), and 1000 (autodetect 1/3)
.endif

.ifndef SAVE_HIGHSCORES
SAVE_HIGHSCORES := 1
.endif

.ifndef AUTO_WIN
; faster aeppoz + press select to end game
AUTO_WIN := 0
.endif

.ifndef KEYBOARD
KEYBOARD := 0
.endif

.ifndef CNROM_OVERRIDE
CNROM_OVERRIDE := 0
.endif

NO_MUSIC := 1

; dev flags
NO_SCORING := 0 ; breaks pace
NO_SFX := 0
NO_MENU := 0
ALWAYS_CURTAIN := 0
QUAL_BOOT := 0
SWAP_DUTY_CYCLES := 0 ; counters the duty cycle swap present in some clone consoles

INITIAL_CUSTOM_LEVEL := 29
INITIAL_LINECAP_LEVEL := 39

; these bytes are currently 2 byte bcd in the menu
; they are swapped and will not work
INITIAL_LINECAP_LINES_LO := $30 ; bcd
INITIAL_LINECAP_LINES_HI := $03 ; bcd (tbd)

BTYPE_START_LINES := $25 ; bcd
MENU_HIGHLIGHT_COLOR := $12 ; $12 in gym, $16 in original
BLOCK_TILES := $7B
EMPTY_TILE := $EF
LOW_STACK_LINE := $DF
TETRIMINO_X_HIDE := $EF

PAUSE_SPRITE_X := $74
PAUSE_SPRITE_Y := $58
; jazzthief-style
; PAUSE_SPRITE_X := $C4
; PAUSE_SPRITE_Y := $16

BUTTON_DOWN := $4
BUTTON_UP := $8
BUTTON_RIGHT := $1
BUTTON_LEFT := $2
BUTTON_B := $40
BUTTON_A := $80
BUTTON_SELECT := $20
BUTTON_START := $10
BUTTON_DPAD := BUTTON_UP | BUTTON_DOWN | BUTTON_LEFT | BUTTON_RIGHT

RENDER_LINES := $01
RENDER_LEVEL := $02
RENDER_SCORE := $04
RENDER_DEBUG := $08
RENDER_HZ := $10
RENDER_STATS := $40
RENDER_HIGH_SCORE_LETTER := $80

.enum
MODE_DEFAULT
MODE_TETRIS
MODE_TSPINS
MODE_PRESETS
MODE_STACKING
MODE_TYPEB
MODE_TAP
MODE_TAPQTY
MODE_TRANSITION
MODE_MARATHON
MODE_DROUGHT
MODE_CHECKERBOARD
MODE_GARBAGE
MODE_LOWSTACK
MODE_KILLX2
MODE_ANYDAS
MODE_SPEED_TEST
.endenum

; .endum
; MODE_FLOOR
; MODE_CRUNCH
; MODE_DAS
; MODE_KILLX2
; MODE_INVISIBLE
; MODE_HARDDROP
; MODE_SCORE_DISPLAY
; MODE_CRASH
; MODE_STRICT
; MODE_HZ_DISPLAY
; MODE_INPUT_DISPLAY
; MODE_DISABLE_FLASH
; MODE_DISABLE_PAUSE
; MODE_DARK
; MODE_GOOFY
; MODE_DEBUG
; MODE_LINECAP
; MODE_DASONLY
; MODE_QUAL
; MODE_PAL
; .if KEYBOARD = 1
; MODE_KEYBOARD
; .endif
; .endenum

.enum
SCORING_CLASSIC
SCORING_LETTERS
SCORING_SEVENDIGIT
SCORING_FLOAT
SCORING_SCORECAP
SCORING_HIDDEN
.endenum

.enum
LINECAP_INACTIVE
LINECAP_KILLX2
LINECAP_FLOOR
LINECAP_INVISIBLE
LINECAP_HALT
.endenum

.enum
LINECAP_OFF
LINECAP_LEVEL
LINECAP_LINES
.endenum

.enum
CRASH_OFF
CRASH_SHOW
CRASH_TOPOUT
CRASH_CRASH
.endenum

LINECAP_WHEN_STRING_OFFSET := $FF
LINECAP_HOW_STRING_OFFSET := $2

MENU_SPRITE_Y_BASE := $46
MENU_MAX_Y_SCROLL := $A0
MENU_TOP_MARGIN_SCROLL := 7 ; in blocks

NTSC_DAS = 16
NTSC_ARR = 6

PAL_DAS = 12
PAL_ARR = 4

.macro MODENAMES
    .byte   "TETRIS"
    .byte   "TSPINS"
    .byte   "SETUPS"
    .byte   "STACKN"
    .byte   "B-TYPE"
    .byte   "QCKTAP"
    .byte   "TAPQTY"
    .byte   "TRNSTN"
    .byte   "MARTHN"
    .byte   "LOBARS"
    .byte   "CKRBRD"
    .byte   "GARBGE"
    .byte   "LOWSTK"
    .byte   "KILLX2"
    .byte   "ANYDAS"
.endmacro
